export const ACTIONS = {
    loaderStart: 'LOADER_START',
	loaderStop: 'LOADER_STOP',
    addPurchaseOrder: 'ADD_PRODUCT',
    deletePurchaseOrder: 'DELETE_PRODUCT',
    editPurchaseOrder: 'EDIT_PRODUCT',
    getPurchaseOrders: 'GET_PRODUCT,',
    getPurchaseOrderWithId: 'GET_PRODUCT_WITH_ID',
    purchaseOrderSuccess: 'PURCHASE_ORDER_SUCCESS',
    purchaseOrderFailed: 'PURCHASE_ORDER_FAILED',
    add: 'ADD',
    delete: 'DELETE',
    edit: 'EDIT',
    get: 'GET,',
    accountType: 'ACCOUNT_TYPE',
    branch: 'BRANCH',
    currency:'CURRENCY',
    productType: 'PRODUCT_TYPE',
    qualityType: 'QUALITY_TYPE',
    taxType: 'TAX_TYPE',
    termHead: 'TERM_HEAD',
    masterSuccess: 'MASTER_SUCCESS',
    masterFailed: 'MASTER_FAILED',
}